baseURL = "https://prepas-mp2i.fr"
title = "Prépas MP2I"
theme = "LoveIt"
defaultContentLanguage = "fr"
languageCode = "fr"
enableRobotsTXT = true
enableGitInfo = true

[menu]
  [[menu.main]]
    name = "MP2I"
    url = "/mp2i/"
    weight = 1
  
  [[menu.main]]
    name = "Informatique"
    url = "/informatique/"
    weight = 2

  [[menu.main]]
    name = "Admission"
    url = "/admission/"
    weight = 3
  
  [[menu.main]]
    name = "Ressources"
    url = "/ressources/"
    weight = 4
  
  # EVENT
  [[menu.main]]
    name = "Forum"
    url = "/forum/"
    weight = 5
  
  [[menu.main]]
    name = "F.A.Q"
    url = "/faq/"
    weight = 6

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

[params]
  version = "0.2.X"
  description = "Site des classes préparatoires MP2I"
  keywords = ["Theme", "Hugo", "MP2I", "Prépa"]
  defaultTheme = "auto"
  gitRepo = "https://github.com/prepas-mp2i/prepas-mp2i.github.io/"
  dateFormat = "02/01/2006"

  [params.app]
    title = "Prépas MP2I"
    noFavicon = false
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = true
    type = "lunr"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      logo = ""
      name = "PREPAS MP2I"
      # add extra information before the name (HTML supported), such as icons
      pre = """<img src='/images/logo.png' alt='Logo' height=25px 
                    style='margin-bottom:-5px;margin-right:5px'>"""
      typeit = true  # typeit animation for title name

  [params.footer]
    enable = true
    hugo = false
    copyright = true
    author = true
    since = 2021
    license = """<a rel="license external nofollow noopener noreffer"
                    href="/mentions-legales/" 
                    target="_blank">Mentions légales</a>"""

  [params.section]
    paginate = 10
    dateFormat = "01-02"

  [params.list]
    paginate = 10
    dateFormat = "01-02"

  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/logo.png"
      title = "Prépas MP2I"
      subtitle = "Bienvenue sur le site des classes préparatoires MP2I !"
      typeit = true
      social = true
      disclaimer = ""

    [params.home.posts]
      enable = true
      paginate = 4

  [params.social]
    GitHub = "prepas-mp2i/prepas-mp2i.github.io"
    Email = "contact@prepas-mp2i.fr"

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    fontawesome = true

  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-7SXBL516N1"  # add your tracking id
      anonymizeIP = false

  [params.cookieconsent]
    enable = false

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
  
[Permalinks]
  posts = ":filename"

[author]
  name = " Étudiants en MP2I"
  email = "contact@prepas-mp2i.fr"

[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

    [markup.goldmark.renderer]
      unsafe = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

  # Options to make output .md files
  [outputFormats.MarkDown]
    mediaType = "text/plain"
    isPlainText = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5