baseURL = "https://prepas-mp2i.fr"  # baseURL shouldn't contains path
title = "Prépas MP2I/MPI"
theme = "LoveIt"
defaultContentLanguage = "fr"
languageCode = "fr"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[menu]
  [[menu.main]]
    pre = """<i class="fas fa-folder-open fa-fw"></i>"""
    url = "/categories/"
    weight = 9

[taxonomies]
  category = "categories"

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'rst2html.py', '^git$']

[params]
  version = "0.2.X"
  description = "Site des classes préparatoires MP2I/MPI"
  detailedDescription = "Site des classes préparatoires MP2I/MPI, créé par des étudiants pour aider les futurs bacheliers à s'orienter et à découvrir cette filière scientifique méconnue. Découvrez notre perspective et toutes les informations nécessaires pour faire votre choix !"
  keywords = ["Theme", "Hugo", "MP2I", "MPI", "Prépa"]
  defaultTheme = "auto"
  gitRepo = "https://github.com/prepas-mp2i/prepas-mp2i.fr/"
  dateFormat = "02/01/2006"

  [params.author]
    name = "Étudiants"
    email = "contact@prepas-mp2i.fr"
    link = "/contact"

  [params.app]
    title = "Prépas MP2I/MPI"
    noFavicon = false
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = true
    type = "lunr"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      name = "PREPAS MP2I/MPI"
      pre = """<img src='/images/logo.png' alt='Logo' height=25px 
                    style='margin-bottom:-5px;margin-right:5px'>"""
      typeit = true  # typeit animation for title name

  [params.footer]
    enable = true
    hugo = false
    copyright = true
    author = true
    since = 2021
    license = """<a rel="license external nofollow noopener noreffer"
                    href="/mentions-legales/" 
                    target="_blank">Mentions légales</a>"""

  [params.section]
    paginate = 10
    dateFormat = "01-02"

  [params.list]
    paginate = 10
    dateFormat = "01-02"

  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/logo.png"
      title = "Prépas MP2I/MPI"
      subtitle = "Bienvenue sur le site des classes préparatoires MP2I/MPI !"
      typeit = true
      social = true

    [params.home.posts]
      enable = true
      paginate = 4

  [params.social]
    GitHub = "prepas-mp2i/prepas-mp2i.fr"
    Email = "contact@prepas-mp2i.fr"
    Discord = "Mu439mBdsv"
    
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    fontawesome = true
    [params.page.share]
      enable = false

  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-7SXBL516N1"  # add your tracking id
      anonymizeIP = false

  [params.cookieconsent]
    enable = false

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
  
[Permalinks]
  posts = '/posts/:slug'
  pages = '/:filename'

[author]
  name = "Étudiants"
  email = "contact@prepas-mp2i.fr"

[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

    [markup.goldmark.renderer]
      unsafe = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

  # Options to make output .md files
  [outputFormats.MarkDown]
    mediaType = "text/plain"
    isPlainText = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
