baseURL = "https://mp2i-france.github.io/mp2i-france-website/"
title = "Pr√©pas MP2I"
theme = "PaperMod"
defaultContentLanguage = "fr"
copyright = "MP2I ‚Äî All rights reserved."
paginate = 4
googleAnalytics = "G-BW19BY0LKC"  # add your tracking id
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = "/:filename/"
  
[params]
  env = "production"  # to enable google analytics, opengraph, twitter-cards and schema.
  keywords = ["MP2I", "PaperMod", "Pr√©pa"]
  description = "Site des classes pr√©paratoires MP2I"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  defaultTheme = "light"  # dark, light
  ShowReadingTime = true

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/mp2i-france/mp2i-france-website"

  [[params.socialIcons]]
    name = "discord"
    url = "https://discord.gg/w4ugrWy84W"

[languages]
  [languages.fr]
    languageName = "French"
    weight = 1

    [languages.fr.homeInfoParams]
      Title = "Bienvenue sur le site des MP2Iüëã"
      Content = """Ce site web est con√ßu par des √©tudiants en classes 
      pr√©paratoires MP2I, il vise une pr√©sentation qualitative de 
      cette nouvelle fili√®re."""

[markup]
    [markup.goldmark.renderer]
      unsafe = true
      
[menu]
  [[menu.main]]
    name = "MP2I"
    url = "/mp2i/"
    weight = 1
  
  [[menu.main]]
    name = "Informatique"
    url = "/informatique/"
    weight = 2

  [[menu.main]]
    name = "Admission"
    url = "/admission/"
    weight = 3
  
  [[menu.main]]
    name = "Ressources"
    url = "/ressources/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
